import type { Metadata } from "next";
import "./globals.css";
import { twMerge } from "tailwind-merge";
import { inter } from "./fonts";

export const metadata: Metadata = {
  title: "SaaS Landing Page Light",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="relative">
      <body className={twMerge(inter.className, "antialiased bg-[#EAEEFE]")}>{children}</body>
    </html>
  );
}
